/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;

import java.io.FileNotFoundException;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    BooksQuote test =new BooksQuote();
//       App test2 =new App();
    @Test void testGetQuote()  {

        try {
            assertEquals("BooksQuote{" +
                    "author='" + test.getAuthor() + '\'' +
                    ", text='" + test.getText() + '\'' +
                    '}', App.getQuote(),"xxxxxxxxxxxxxxxxxxxxxxxx"
        );
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }



}
